### ISSUE TITLE
[devOps]API 서버 CD 파이프라인 구축하기

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#140]

**Comment by atoye1** [comment]
Docker build and push 액션에서 Dockerfile을 계속 인식하지 못하는 이슈가 발생했음.

커스텀으로 정의한 debug step을 통해서 리눅스 커맨드 `ls -al`실행해서 폴더 내용을 확인하여 디버깅함.

`checkout@v2` 를 호출하지 않아
도커빌더가 깃 리포의 코드를 인식하지 못하는 문제 발생했음.
해당 액션을 실행시켜주면서 해결했음

env의 working-directory와 `docker/build-push-action@v3`는 의도한대로 동작하는 것을 확인

```
name: serverCI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - server/src**

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: debug
        run: ls -al
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: snowdelver/eweapi:latest
```
